### ISSUE TITLE
前端接口问题交流

### ISSUE THREAD

**Issue by anandzhang** [wangsiqian/issue_feedback_sanic#33]
收集前端开发所产生的意见

**Comment by anandzhang** [comment]
# 前端界面目前所使用到的API

## 主页
1. 列出所有反馈信息
> 反馈信息需要产品id，现在临时使用的是产品列表中的第一个产品
2. 用户登录后的统计信息
> USER：用户提出的反馈数、用户收到的点赞数
MANAGER：管理员回复的反馈数、管理的产品数
DEVELOPER：开发人员认领的反馈总数、正在处理的反馈数
3. 用户提交反馈（创建反馈）

## 个人中心
1. 查询用户资料
2. 统计数据：和主页的类似
3. 个人中心详细信息
> USER：提出的反馈、收到的回复
MANAGER：回复的反馈、删除的反馈
DEVELOPER：处理中的反馈、已解决的反馈

## 后台管理
### 首页
统计信息
### 反馈管理
1. 反馈列表
2. 筛选反馈
### 产品管理
1. 产品列表
2. 添加产品
### 后台成员
1. 创建管理员、开发人员
2. 成员列表

**Comment by anandzhang** [comment]
创建产品、创建反馈这类的API可以在返回的 `result` 字段中返回创建好的这个产品/反馈信息。
这样我可以不需要重新请求产品列表、反馈列表的接口，直接把返回回来的 `result` 追加到已经获取过的列表状态中。
@wangsiqian

**Comment by anandzhang** [comment]
另外，资源创建成功后，既然返回了 `message` 字段，那么可以不为空，给出真实的 `message` 信息。
以下是当前 API 的 `Response` 情况：

```json
{
    "ok": true,
    "message": "",
    "result": {}
}
```

`message` 可以像创建资源失败一样给出 `message` 信息。
@wangsiqian

**Comment by wangsiqian** [comment]
第一个列出所有issue 前端还是先按产品分开吧，首页就是现有的产品模块，让用户点击哪个产品就去看相关反馈

**Comment by onekx** [comment]
> 第一个列出所有issue 前端还是先按产品分开吧，首页就是现有的产品模块，让用户点击哪个产品就去看相关反馈

这样也可以

**Comment by anandzhang** [comment]
## 产品的唯一性

![image](https://user-images.githubusercontent.com/33146742/83739937-cb9c4280-a688-11ea-8f0c-0c1fd2783fda.png)

产品创建没有限制名称的唯一，是否需要进行限制？ @wangsiqian @onekx

**Comment by anandzhang** [comment]
查询用户资料 API 返回的字段中请求添加 `role_id` 字段。
> `role_id` 字段在 `/login` API 用户登录接口所返回，这时存放它没有了意义，因为 `role_id` 不在存放于 `localStorage` 中而是存在于 `Redux` 状态库。
所以当用户刷新页面，记住用户登录状态的功能无效。
用户登录接口得到的 `role_id` 只是一个状态，已经丢失，而 `/profile` API 没有 `role_id`  字段返回，无法更新组件状态的 `role_id` ，导致用户无法进入个人中心。
