### ISSUE TITLE
创建资源的API 返回创建好的资源

### ISSUE THREAD

**Issue by anandzhang** [wangsiqian/issue_feedback_sanic#55]
**请求**

| 方法 | URL | Body |
| ---- | ---- | ---- |
| POST | /v1/comment | user_id<br />issue_id<br />content |

**响应**

```json
{
    "ok": true,
    "result": {
        "comment_id": "a8539545-2af7-4c7a-be93-c0a50c308579"
    }
}
```

**理想的响应**

```json
{
    "ok": true,
    "result": {
        "owner": {
            "user_id": "fcbc5c4f-f873-4a71-8d9f-258278382c9b",
            "nickname": "user@837189",
            "avatar": ""
        },
        "content": "demo",
        "comment_id": "78c408d5-7c8f-48ce-807d-ac29927067df",
        "created_at": "2020-06-04T13:41:12.177000"
    }
}
```

**Comment by anandzhang** [comment]
另外创建反馈 `/v1/issue` 、创建产品 `/v1/product` 同理。

**Comment by wangsiqian** [comment]
可以多返回一个created_at 创建者的信息和content前端都有吧

**Comment by anandzhang** [comment]
创建者的信息需要另取，创建评论的表单只有 `content` 。
所以，前端直接能拿到 `content` ，对于 `owner` 字段需要从状态库中另取。
你直接返回创建的资源的所有字段吧，这个你很好操作吧。

创建反馈、创建产品这些前端自己组合的话不必要的操作，直接存你的响应是比较好的解决方法。

**Comment by anandzhang** [comment]
有这个需求的主要目的：
用户创建评论，发生创建请求，得到你的响应添加到原本存在的评论列表中，这样就避免了再次请求列表。
又或者当项目部署后，如果创建资源都需要：创建请求 -> 请求列表（响应size较大） -> 整个列表状态渲染。这样用户等待时间很长。
