### ISSUE TITLE
关于查询用户资料 API

### ISSUE THREAD

**Issue by anandzhang** [wangsiqian/issue_feedback_sanic#56]
**请求**

| 方法 | URL | Body |
| ---- | ---- | ---- |
| GET| /v1/profile/<user_id> | |

**响应**

```json
{
    "ok": true,
    "result": {
        "gender": 1,
        "avatar": "",
        "user_id": "f526fff7-4780-40e6-90d8-aba12d2b386f",
        "nickname": "user@667980"
    }
}
```

**需求**
能否将 `/v1/account/<user_id>/role`  接口结合到查询用户资料的响应中。
每次第一次加载页面都进行这两次请求，外加页面其他数据的请求，就发出了很多请求，是否能进行简化。

**Comment by wangsiqian** [comment]
不是列表嵌套 就没必要跨域整合数据

**Comment by anandzhang** [comment]
前端页面的请求产生得太多了，这个 `roleId` 完全可以放到 `profile` 里一起返回。
什么是列表嵌套？

**Comment by wangsiqian** [comment]
不是列表嵌套需要多次查询 就不整合，只能说这个项目不适合这种架构做，或者不适合用 nosql, 没办法，再做已经没有微服务的影子了，后面代码耦合在一起，完全没办法拆，这本来就是两个领域里面的数据。

**Comment by anandzhang** [comment]
那还是需要考虑打包接口吧
