### ISSUE TITLE
产品删除问题

### ISSUE THREAD

**Issue by anandzhang** [wangsiqian/issue_feedback_sanic#73]
**请求**

| 方法 | URL | Body |
| ---- | ---- | ---- |
| DELETE | /v1/product/<product_id> | manager_id |

**问题**

删除产品后，获取产品列表，这个产品确实已经不存在，但是通过 `product_id` 去查询产品反馈列表时依然能得到删除了的产品的反馈列表。

**Comment by wangsiqian** [comment]
这个可以不用管，删除了这个产品 id就拿不到了，后面会做一些访问限制，反馈列表不会清除

**Comment by anandzhang** [comment]
OKOK
