### ISSUE TITLE
统计数据 API

### ISSUE THREAD

**Issue by anandzhang** [wangsiqian/issue_feedback_sanic#77]

**Comment by anandzhang** [comment]
用户界面主页：

跟随个人中心中每项列表的 `count` 数

**Comment by anandzhang** [comment]
后台管理页面：

1. 今日用户反馈
2. 今日受理反馈（用户提出反馈，管理员把这个反馈分配给开发人员数）
3. 今日开发人员处理

**Comment by anandzhang** [comment]
![image](https://user-images.githubusercontent.com/33146742/85141398-495f7100-b279-11ea-8b5e-df364c9cf6f3.png)


> 后台管理页面：
> 
> 1. 今日用户反馈
> 2. 今日受理反馈（用户提出反馈，管理员把这个反馈分配给开发人员数）
> 3. 今日开发人员处理

这个没做

**Comment by wangsiqian** [comment]
> ![image](https://user-images.githubusercontent.com/33146742/85141398-495f7100-b279-11ea-8b5e-df364c9cf6f3.png)
> 
> > 后台管理页面：
> > 
> > 1. 今日用户反馈
> > 2. 今日受理反馈（用户提出反馈，管理员把这个反馈分配给开发人员数）
> > 3. 今日开发人员处理
> 
> 这个没做

这个接口是有的
